#
# Module manifest for module 'PwshInit'
#
# Generated by: adamcheney
#
# Generated on: 20251210
#

@{
    RootModule = 'PwshInit.psm1'
    GUID = 'ff91b784-5151-488c-83e4-580a72e1ce89'
    ModuleVersion = '0.1.0'
    Author = 'Adam Cheney'
    Description = 'Bootstrap helpers for Powershell used by repository bootstrap scripts.'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    ScriptsToProcess = @()
    FunctionsToExport = @(
        'Ensure-ModuleVersionImport'
        'Ensure-ModuleVersionInstall'
        'Set-PSResourceGetV3'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags = @('Pwsh','Bootstrap','Infrastructure')
            ProjectUri = 'https://github.com/adamcheney/AKS_practice/'
            LicenseUri = ''
            ReleaseNotes = 'Initial manifest'
        }
    }
}