#
# Module manifest for module 'BootstrapState'
#
# Generated by: adamcheney
#
# Generated on: 20251220
#

@{
    RootModule = 'BootstrapState.psm1'
    GUID = 'f81cd16d-47b5-4c37-a23a-0956aadb26d9'
    ModuleVersion = '0.1.0'
    Author = 'Adam Cheney'
    Description = 'State file management for AKS bootstrap.'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    ScriptsToProcess = @()
    FunctionsToExport = @(
        'Clear-InfraState'
        'Get-InfraState'
        'Set-InfraState'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags = @('Pwsh','Bootstrap','Infrastructure')
            ProjectUri = 'https://github.com/adamcheney/AKS_practice/'
            LicenseUri = ''
            ReleaseNotes = 'Initial manifest'
        }
    }
}